# 使用更轻量级的基础镜像
FROM eclipse-temurin:21-jre-alpine

# 作者信息
LABEL maintainer="zmxccxy <zmxccxy@aliyun.com>"

# 定义构建时变量
ARG APP_VERSION=1.0

# 设置环境变量
ENV APP_ENV=production
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk

# 更新并安装必需的软件（例如 curl、bash）
RUN apk update && apk add --no-cache bash curl

# 创建并设置工作目录
WORKDIR /nas-fmt

# 将打包后的 JAR 文件复制到容器中
COPY target/media-rename-0.0.1.jar /nas-fmt/media-rename-0.0.1.jar

# 暴露端口
EXPOSE 8080

# 设置容器启动时执行的命令
ENTRYPOINT ["java", "-jar", "/nas-fmt/media-rename-0.0.1.jar"]

# 健康检查（可选）
HEALTHCHECK CMD curl --fail http://localhost:8080/health || exit 1

# 设置容器停止时的信号
STOPSIGNAL SIGTERM

# 设置挂载点（可选）
VOLUME ["/nas-fmt/data"]

# 配置容器的用户权限（可选）
USER root

# 定义默认 JVM 参数（例如，最大内存限制）
CMD ["-Xmx512m"]

# 打包时清理（删除不必要的缓存）
RUN rm -rf /var/cache/apk/*